return {
  {
    ['key'] = '1',
    ['type'] = 'roll',
    ['name'] = "Samurai Roll",
    ['help'] = 'Store TP',
  },
  {
    ['key'] = '2',
    ['type'] = 'roll',
    ['name'] = "Hunter's Roll",
    ['help'] = 'Accuracy/Ranged accuracy',
  },
  {
    ['key'] = '3',
    ['type'] = 'roll',
    ['name'] = "Warlock's Roll",
    ['help'] = 'Magic accuracy',
  },
  {
    ['key'] = '4',
    ['type'] = 'roll',
    ['name'] = "Wizard's Roll",
    ['help'] = 'Magic attack',
  },
  {
    ['key'] = '5',
    ['type'] = 'roll',
    ['name'] = "Evoker's Roll",
    ['help'] = 'Refresh',
  },
  {
    ['key'] = '6',
    ['type'] = 'roll',
    ['name'] = "Tactician's Roll",
    ['help'] = 'Regain',
  },
  {
    ['key'] = '7',
    ['type'] = 'ja',
    ['name'] = 'Triple shot',
    ['help'] = 'Occ. use three ammo',
  },
  {
    ['key'] = '8',
    ['type'] = 'ja',
    ['name'] = 'Fold',
    ['help'] = 'Removes bust, or last roll',
  },
  {
    ['key'] = '9',
    ['type'] = 'ja',
    ['name'] = 'Snake eye',
    ['help'] = 'Next roll is 1',
  },
  {
    ['key'] = '0',
    ['type'] = 'ja',
    ['name'] = 'Double-up',
    ['help'] = 'Increases last roll',
  },
  {
    ['key'] = '!1',
    ['type'] = 'roll',
    ['name'] = "Bolter's Roll",
    ['help'] = 'Movement speed',
  },
  {
    ['key'] = '!2',
    ['type'] = 'roll',
    ['name'] = "Chaos Roll",
    ['help'] = 'Attack',
  },
  {
    ['key'] = '!3',
    ['type'] = 'roll',
    ['name'] = "Fighter's Roll",
    ['help'] = 'Double attack',
  },
  {
    ['key'] = '!4',
    ['type'] = 'roll',
    ['name'] = "Dancer's Roll",
    ['help'] = 'Regen',
  },
  {
    ['key'] = '!5',
    ['type'] = 'roll',
    ['name'] = "Drachen Roll",
    ['help'] = 'Pet accuracy',
  },
  {
    ['key'] = '!6',
    ['type'] = 'roll',
    ['name'] = "Beast Roll",
    ['help'] = 'Pet attack',
  },
  {
    ['key'] = '!7',
    ['type'] = 'roll',
    ['name'] = "Puppet Roll",
    ['help'] = 'Pet magic attack/accuracy',
  },
  {
    ['key'] = '!8',
    ['type'] = 'roll',
    ['name'] = "Companion's Roll",
    ['help'] = 'Pet regen/regain',
  },

  {
    ['key'] = '!9',
    ['type'] = 'roll',
    ['name'] = "Gallant's Roll",
    ['help'] = 'Defense',
  },
  {
    ['key'] = '!0',
    ['type'] = 'roll',
    ['name'] = "Blitzer's Roll",
    ['help'] = 'Attack delay',
  },
  {
    ['key'] = '!-',
    ['type'] = 'roll',
    ['name'] = "Magus's Roll",
    ['help'] = 'Magic defense',
  },
  {
    ['key'] = '!=',
    ['type'] = 'roll',
    ['name'] = "Corsair's Roll",
    ['help'] = 'Exp/CP',
  },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Courser's Roll",
  --   ['help'] = 'Snapshot',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Runeist's Roll",
  --   ['help'] = 'Magic evasion',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Allies' Roll",
  --   ['help'] = 'Skillchain damage',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Ninja's Roll",
  --   ['help'] = 'Evasion',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Caster's Roll",
  --   ['help'] = 'Fast cast',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Healer's Roll",
  --   ['help'] = 'Cure potency',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Choral Roll",
  --   ['help'] = 'Spell interuption',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Monk's Roll",
  --   ['help'] = 'Subtle blow',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Scholar's Roll",
  --   ['help'] = 'Conserve MP',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Naturalist's Roll",
  --   ['help'] = 'Enhancing magic duration',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Miser's Roll",
  --   ['help'] = 'Save TP',
  -- },
  -- {
  --   ['key'] = '',
  --   ['type'] = 'roll',
  --   ['name'] = "Avenger's Roll",
  --   ['help'] = 'Counter',
  -- },
  {
    ['key'] = '`',
    ['type'] = 'raw',
    ['command'] = '/ra <t>',
  },
  {
    ['key'] = '^`',
    ['type'] = 'raw',
    ['command'] = '/ws "Leaden Salute" <t>',
  },
  {
    ['key'] = '!`',
    ['type'] = 'raw',
    ['command'] = '/ws "Last Stand" <t>',
  },
  {
    ['key'] = '^!`',
    ['type'] = 'raw',
    ['command'] = '/ws "Wildfire" <t>',
  },
}
